name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true
      - name: Build
        run: |
          if [ "${{ github.repository }}" = "SAP-docs/preview.developer.concur.com" ]; then
            bundle exec jekyll build
          else
            bundle exec jekyll build --baseurl "/${{ github.event.repository.name }}"
          fi
      - name: Place CNAME
        if: github.repository == 'SAP-docs/preview.developer.concur.com'
        run: echo "preview.developer.concur.com" > _site/CNAME
      - name: Disable Jekyll on GitHub Pages
        run: touch _site/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
